name: Android Instrumented Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  android-test:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: ${{ runner.temp }}/Android

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Install Android SDK command line tools
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip wget
          mkdir -p $ANDROID_HOME/cmdline-tools/latest
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools/latest
          export PATH=$ANDROID_HOME/cmdline-tools/latest/cmdline-tools/bin:$ANDROID_HOME/platform-tools:$PATH
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-33" "system-images;android-33;google_apis;x86_64"

      - name: Create AVD
        run: |
          export PATH=$ANDROID_HOME/cmdline-tools/latest/cmdline-tools/bin:$ANDROID_HOME/platform-tools:$PATH
          echo "no" | avdmanager create avd \
            --name test-emulator-${{ github.run_id }} \
            --package "system-images;android-33;google_apis;x86_64" \
            --device "pixel" \
            --force

      - name: Start Emulator
        run: |
          export PATH=$ANDROID_HOME/cmdline-tools/latest/cmdline-tools/bin:$ANDROID_HOME/platform-tools:$PATH
          $ANDROID_HOME/emulator/emulator -avd test-emulator-${{ github.run_id }} \
            -no-window -no-audio -no-snapshot \
            -gpu swiftshader_indirect -memory 2048 -no-boot-anim &
          EMULATOR_PID=$!
          echo "Waiting for emulator to boot..."
          adb wait-for-device
          boot_completed=""
          while [ "$boot_completed" != "1" ]; do
            sleep 5
            boot_completed=$(adb shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')
            echo "Boot completed: $boot_completed"
          done
          echo "Emulator is ready!"

      - name: Run Android Instrumented Tests
        run: |
          ./gradlew connectedAndroidTest --stacktrace

      - name: Stop Emulator
        if: always()
        run: |
          adb -s emulator-5554 emu kill || true
