name: Android CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    name: Build & Test on Emulator
    runs-on: macOS-latest

    steps:
      # 1. コードチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. JDK 17 セットアップ
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3. gradlew を実行可能に
      - name: Make gradlew executable
        run: chmod +x ./DigitalKey/gradlew

      # 4. Android SDK セットアップ
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          build-tools: "33.0.2"
          ndk: "25.2.9519653"

      # 5. プロジェクトをビルド
      - name: Build project
        run: ./gradlew assembleDebug --stacktrace
        working-directory: ./DigitalKey

      # 6. Emulator を起動して Instrumentation Test を実行
      - name: Run instrumentation tests on emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          force-avd-creation: true
          emulator-options: "-no-window -no-audio -no-boot-anim"
          script: ./gradlew connectedCheck --stacktrace
          working-directory: ./DigitalKey
