name: Android CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          build-tools-version: 33.0.2
          ndk-version: 25.2.9519653

      - name: Install Emulator & System Image
        run: |
          yes | sdkmanager --install "system-images;android-30;google_apis;x86_64"
          sdkmanager --update

      - name: Start Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          arch: x86_64
          target: google_apis
          profile: Pixel_4_API_30
          emulator-options: -no-window -no-accel
          wait-for-boot: true
          max-wait: 600

      - name: Run Instrumented Tests
        run: ./gradlew connectedAndroidTest

      - name: Stop Emulator
        run: adb -s emulator-5554 emu kill || true
