name: Android Emulator CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  android-emulator:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      # 1. Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3. Cache Gradle dependencies
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # 4. Set up Android SDK (no inputs)
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      # 5. Run Emulator and Connected Tests
      - name: Run Emulator and Connected Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          arch: x86_64
          target: google_apis
          profile: Pixel_4_API_30
          emulator-options: -no-window -no-accel
          disable-linux-hw-accel: true
          emulator-boot-timeout: 600
          script: |
            # Wait for device
            adb wait-for-device
            # Wait until boot completed
            adb shell 'while [[ $(getprop sys.boot_completed) != "1" ]]; do sleep 5; done;'
            # Run connected Android tests
            ./gradlew connectedAndroidTest
