name: Android CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. ソースコードチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. JDK 1.8 インストール
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: temurin

      # 3. Android SDK セットアップ
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 25
          build-tools: 33.0.2
          ndk: 21.4.7075529
          cmake: 3.22.1

      # 4. Gradle ビルド
      - name: Build APK
        run: ./gradlew assembleDebug --stacktrace

      # 5. エミュレータ起動とテスト
      - name: Run instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 25
          target: default
          arch: x86
          script: ./gradlew connectedCheck --stacktrace
          emulator-options: -no-window -gpu swiftshader_indirect
