name: Android Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: $HOME/Android
      PATH: $HOME/Android/platform-tools:$HOME/Android/cmdline-tools/latest/bin:$PATH

    steps:
    # 1. リポジトリチェックアウト
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. JDK 17 をセットアップ
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    # 3. Android SDK コマンドラインツールをインストール
    - name: Install Android SDK
      run: |
        mkdir -p $ANDROID_HOME/cmdline-tools
        cd $ANDROID_HOME/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip
        mv cmdline-tools latest
        rm cmdline-tools.zip
      shell: bash

    # 4. 必要な SDK パッケージをインストール
    - name: Install SDK packages
      run: |
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"
      shell: bash

    # 5. Gradle キャッシュ
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper/
        key: gradle-${{ runner.os }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

    # 6. UnitTest 実行
    - name: Run Unit Tests
      run: ./gradlew testDebugUnitTest
