name: Android CI (macOS Runner)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  android-ci:
    runs-on: macos-latest

    steps:
      # ① ソースコード取得
      - name: Checkout repository
        uses: actions/checkout@v4

      # ② JDK17 セットアップ（AGP 8.x 対応）
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # ③ Android SDK セットアップ
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # ④ Gradle キャッシュ
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}

      # ⑤ エミュレータ起動 & AndroidTest + Jacoco レポート生成
      - name: Run Instrumented Tests & Jacoco
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: pixel             # macOS runner での安定プロファイル
          avd-name: test-avd         # シンプルなAVD名
          force-avd-creation: true
          emulator-boot-timeout: 600
          emulator-port: 5554
          emulator-options: -no-window
          disable-animations: true
          script: ./gradlew connectedDebugAndroidTest jacocoAndroidTestReport

      # ⑥ Jacoco レポートをアーティファクトとして保存
      - name: Upload Jacoco Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: DigitalKey/app/build/reports/jacoco/androidTest
