name: Android CI (macOS ARM)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  android-ci:
    runs-on: macos-latest  # Apple Silicon

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}

      - name: Run Instrumented Tests & Jacoco
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: arm64-v8a       # ARM64
          profile: Pixel
          avd-name: test-avd
          force-avd-creation: true
          emulator-boot-timeout: 600
          emulator-options: -no-window
          disable-animations: true
          script: ./gradlew connectedDebugAndroidTest jacocoAndroidTestReport

      - name: Upload Jacoco Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: DigitalKey/app/build/reports/jacoco/androidTest
