name: Android Emulator CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  android-emulator:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      # 1. Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3. Cache Gradle dependencies
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # 4. Install Android SDK packages explicitly
      - name: Install Android SDK packages
        run: |
          sudo mkdir -p /opt/android-sdk
          sudo chown $USER:$USER /opt/android-sdk
          sudo apt-get update
          sudo apt-get install -y unzip wget
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d /opt/android-sdk
          mv /opt/android-sdk/cmdline-tools /opt/android-sdk/cmdline-tools-latest
          export ANDROID_SDK_ROOT=/opt/android-sdk
          yes | /opt/android-sdk/cmdline-tools-latest/bin/sdkmanager --licenses
          /opt/android-sdk/cmdline-tools-latest/bin/sdkmanager "platform-tools" "platforms;android-30" "system-images;android-30;google_apis;x86_64" "emulator"

      # 5. Run Emulator and Connected Tests
      - name: Run Emulator and Connected Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          arch: x86_64
          target: google_apis
          profile: Pixel_4_API_30
          force-avd-creation: true
          emulator-options: -no-window -no-accel -gpu swiftshader_indirect
          disable-linux-hw-accel: true
          emulator-boot-timeout: 600
          script: |
            echo "Waiting for emulator boot..."
            adb wait-for-device
            adb shell 'while [[ $(getprop sys.boot_completed) != "1" ]]; do sleep 5; done;'
            echo "Emulator booted, running tests"
            ./gradlew connectedAndroidTest
