name: Android Emulator CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  android-emulator:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      # 1. Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3. Cache Gradle dependencies
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # 4. Install Android SDK packages explicitly
      - name: Install Android SDK packages
        run: |
          export ANDROID_SDK_ROOT=/opt/android-sdk
          sudo mkdir -p $ANDROID_SDK_ROOT
          sudo chown $USER:$USER $ANDROID_SDK_ROOT

          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools
          mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest

          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT \
            "platform-tools" \
            "platforms;android-30" \
            "system-images;android-30;google_apis;x86_64" \
            "emulator"

      # 5. Run Emulator and Connected Tests
      # 省略：Checkout 〜 Emulator 起動までは同じ

      - name: Run Emulator and Connected Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          arch: x86_64
          target: google_apis
          avd-name: test
          force-avd-creation: true
          emulator-options: -no-window -no-accel -gpu swiftshader_indirect
          disable-linux-hw-accel: true
          emulator-boot-timeout: 600
          cores: 2
          disable-animations: true
          script: |
            echo "Waiting for emulator boot..."
            adb wait-for-device
            adb shell 'while [[ $(getprop sys.boot_completed) != "1" ]]; do sleep 5; done;'
            echo "Emulator booted, running tests"
            
            # プロジェクトディレクトリに移動
            cd DigitalKey
            chmod +x ./gradlew
            ./gradlew connectedAndroidTest
